Repository AY2223S1-CS2113-F11-1/tp, pull requests merged in 2022-10, with the labels that each got.

#37 Implement function to store added client to text file.
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/CommandAddClient.java
Labels: type.Chore, priority.High

#40 Add update file function for Client
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/CommandDeleteClient.java
Labels: type.Chore, priority.High

#46 Implement storing, updating and loading feature for pairing/unpairing…
  src/main/java/seedu/duke/PairingList.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/CommandPair.java
  src/main/java/seedu/duke/command/CommandUnpair.java
Labels: type.Chore, priority.High

#49 Add store and load function for property
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/CommandAddClient.java
  src/main/java/seedu/duke/command/CommandAddProperty.java
Labels: type.Chore, priority.High

#50 Branch delete property
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/PropertyList.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/CommandDeleteProperty.java
  src/main/java/seedu/duke/exception/EmptyPropertyIndexDeleteException.java
  src/main/java/seedu/duke/exception/InvalidClientIndexDeleteException.java
  src/main/java/seedu/duke/exception/InvalidPropertyIndexDeleteException.java
  src/main/java/seedu/duke/exception/InvalidPropertyIndexFlagFormatException.java
  src/main/java/seedu/duke/exception/MissingPropertyIndexFlagException.java
Labels: type.Story, priority.High

#52 Add function to update property when property array list change
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/CommandDeleteProperty.java
Labels: type.Chore, priority.High

#58 Branch update pairing
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/PairingList.java
  src/main/java/seedu/duke/PropertyList.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/CommandAddClient.java
  src/main/java/seedu/duke/command/CommandDeleteClient.java
  src/main/java/seedu/duke/command/CommandDeleteProperty.java
Labels: type.Bug, priority.Medium, severity.High

#60 Add simple logging for CommandAddProperty and CommandAddClient
  src/main/java/seedu/duke/command/CommandAddClient.java
  src/main/java/seedu/duke/command/CommandAddProperty.java
Labels: type.Chore, priority.Medium

#62 Add simple assertions for CommandAddProperty and CommandAddClient
  src/main/java/seedu/duke/command/CommandAddClient.java
  src/main/java/seedu/duke/command/CommandAddProperty.java
Labels: type.Chore, priority.Medium

#64 Branch pair test
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/PairingList.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/exception/AlreadyPairedException.java
  src/main/java/seedu/duke/exception/InvalidIndexException.java
  src/main/java/seedu/duke/exception/NotValidIndexException.java
  src/main/java/seedu/duke/exception/PropertyAlreadyPairedException.java
  src/test/java/seedu/duke/PairingListTest.java
Labels: type.Chore, priority.Medium

#66 Add test for Command Add Client
  src/main/java/seedu/duke/command/CommandAddClient.java
  src/test/java/seedu/duke/command/CommandAddClientTest.java
Labels: type.Chore, priority.Medium

#65 Add test for Command Add Property
  src/test/java/seedu/duke/command/CommandAddPropertyTest.java
Labels: type.Chore, priority.Medium

#69 Change PairingList to take in Objects instead of String
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/PairingList.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/CommandAddProperty.java
  src/main/java/seedu/duke/command/CommandBye.java
  src/main/java/seedu/duke/command/CommandCheckProperty.java
  src/main/java/seedu/duke/command/CommandDeleteClient.java
  src/main/java/seedu/duke/command/CommandDeleteProperty.java
  src/main/java/seedu/duke/command/CommandPair.java
  src/main/java/seedu/duke/command/CommandUnpair.java
  src/test/java/seedu/duke/PairingListTest.java
  src/test/java/seedu/duke/command/CommandAddClientTest.java
Labels: type.Enhancement, priority.Medium

#80 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Chore, priority.Medium

#86 Remove brackets when loading to pairingList
  src/main/java/seedu/duke/Storage.java
Labels: type.Bug, severity.VeryLow

#87 Branch parser refactoring
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/parsermanager/ParseAddClient.java
  src/main/java/seedu/duke/parsermanager/ParseAddProperty.java
  src/main/java/seedu/duke/parsermanager/ParseCheckProperty.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteClient.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteProperty.java
  src/main/java/seedu/duke/parsermanager/ParseExit.java
  src/main/java/seedu/duke/parsermanager/ParseListClient.java
  src/main/java/seedu/duke/parsermanager/ParseListProperty.java
  src/main/java/seedu/duke/parsermanager/ParsePair.java
  src/main/java/seedu/duke/parsermanager/ParseUndefined.java
  src/main/java/seedu/duke/parsermanager/ParseUnpair.java
  src/main/java/seedu/duke/parsermanager/Parser.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
Labels: type.Enhancement, type.Chore, priority.Medium

#93 Branch budget checker
  src/main/java/seedu/duke/CommandStructure.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/PairingList.java
  src/main/java/seedu/duke/exception/BudgetExceededException.java
  src/main/java/seedu/duke/parsermanager/ParsePair.java
  src/main/java/seedu/duke/parsermanager/Parser.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
  src/test/java/seedu/duke/PairingListTest.java
Labels: type.Bug, severity.Low

#96 Branch fix parser add discrepancies
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parsermanager/ParseAdd.java
  src/main/java/seedu/duke/parsermanager/ParseAddClient.java
  src/main/java/seedu/duke/parsermanager/ParseAddProperty.java
Labels: type.Bug, severity.Medium

#97 Show deleted pairs when deleting
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/CommandDeleteClient.java
  src/main/java/seedu/duke/command/CommandDeleteProperty.java
Labels: type.Bug, severity.Medium

#99 Update Design and Implementation portion for Storage
  docs/DeveloperGuide.md
  docs/diagrams/LoadFileFlowChart.jpg
  docs/diagrams/StorageAddClientSequenceDiagram.jpg
  docs/diagrams/StorageAddPairSequenceDiagram.jpg
  docs/diagrams/StorageAddPropertySequenceDiagram.jpg
  docs/diagrams/StorageDesignDiagram.jpg
  docs/diagrams/StorageUpdateClientSD.jpg
  docs/diagrams/StorageUpdatePairSD.jpg
  docs/diagrams/StorageUpdatePropertySD.jpg
Labels: type.Chore, priority.High

#101 Add Delete Client/Property to Implementation section in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteClientPropertyCD.png
  docs/diagrams/DeleteClientSD.png
  docs/diagrams/DeletePropertySD.png
Labels: type.Chore, priority.High

#102 Branch developer guide
  docs/DeveloperGuide.md
  docs/diagrams/PairingListAddPairSequenceDiagram.png
  docs/diagrams/PairingListDesignDiagram.png
Labels: priority.High

#107 Add Developer Guide (Draft) for Add Feature in Implementation section
  docs/DeveloperGuide.md
  docs/diagrams/AddClientSequenceDiagram.JPG
  docs/diagrams/AddPropertySequenceDiagram.JPG
  docs/diagrams/CommandAddRelatedClassesDiagram.jpg
  docs/diagrams/ParseAddRelatedClassesDiagram.jpg
Labels: type.Chore, priority.High

#104 Implement 'find' feature to query for matching clients
  src/main/java/seedu/duke/CommandStructure.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/CommandFindClient.java
  src/main/java/seedu/duke/parsermanager/ParseFindClient.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
Labels: type.Chore, priority.Medium

#111 Show property details when checking property
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/CommandCheckProperty.java
Labels: type.Bug, severity.Medium

#114 Implement checking function for valid input to load into Client, Prop…
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/CommandDeleteClient.java
  src/main/java/seedu/duke/command/CommandDeleteProperty.java
  src/main/java/seedu/duke/command/CommandUnpair.java
  src/main/java/seedu/duke/parsermanager/ParsePair.java
Labels: type.Bug, severity.High

#122 Add style.puml and Architecture Diagram (work in progress)
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.png
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/PairingListAddPairSD.png
  docs/diagrams/PairingListAddPairSequenceDiagram.png
  docs/diagrams/PairingListAddSD.puml
  docs/diagrams/PairingListCD.puml
  docs/diagrams/style.puml
Labels: priority.High

#112 Implement Check Client
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/CommandCheckClient.java
  src/main/java/seedu/duke/parsermanager/ParseCheckClient.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
Labels: type.Story, priority.High

#134 Add User Guide draft for Add Features
  docs/UserGuide.md
  src/main/java/seedu/duke/Messages.java
Labels: type.Chore, priority.High

#135 Add Storage and Find features in User Guide
  docs/UserGuide.md
Labels: type.Chore, priority.High

#138 Extract common methods for parser
  src/main/java/seedu/duke/parsermanager/ParseAdd.java
  src/main/java/seedu/duke/parsermanager/ParseCheckClient.java
  src/main/java/seedu/duke/parsermanager/ParseCheckProperty.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteClient.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteProperty.java
  src/main/java/seedu/duke/parsermanager/ParsePair.java
  src/main/java/seedu/duke/parsermanager/ParseUnpair.java
  src/main/java/seedu/duke/parsermanager/Parser.java
Labels: type.Chore, priority.Medium

#140 Remove the deletion of object in Storage Sequence Diagram
  docs/diagrams/StorageAddClientSequenceDiagram.jpg
  docs/diagrams/StorageAddPairSequenceDiagram.jpg
  docs/diagrams/StorageAddPropertySequenceDiagram.jpg
  docs/diagrams/StorageUpdateClientSD.jpg
  docs/diagrams/StorageUpdatePairSD.jpg
  docs/diagrams/StorageUpdatePropertySD.jpg
Labels: type.Bug, severity.Medium

#143 Modify parse add related exceptions as class based exceptions
  src/main/java/seedu/duke/command/CommandAdd.java
  src/main/java/seedu/duke/command/CommandAddClient.java
  src/main/java/seedu/duke/command/CommandAddProperty.java
  src/main/java/seedu/duke/exception/DuplicateClientException.java
  src/main/java/seedu/duke/exception/DuplicatePropertyException.java
  src/main/java/seedu/duke/exception/EmptyAddClientDetailException.java
  src/main/java/seedu/duke/exception/EmptyAddPropertyDetailException.java
  src/main/java/seedu/duke/exception/IncorrectAddClientFlagOrderException.java
  src/main/java/seedu/duke/exception/IncorrectAddPropertyFlagOrderException.java
  src/main/java/seedu/duke/exception/InvalidBudgetFormatException.java
  src/main/java/seedu/duke/exception/InvalidContactNumberException.java
  src/main/java/seedu/duke/exception/InvalidEmailException.java
  src/main/java/seedu/duke/exception/InvalidPriceFormatException.java
  src/main/java/seedu/duke/exception/InvalidSingaporeAddressException.java
  src/main/java/seedu/duke/exception/InvalidUnitTypeLabelException.java
  src/main/java/seedu/duke/exception/MissingAddClientFlagException.java
  src/main/java/seedu/duke/exception/MissingAddPropertyFlagException.java
  src/main/java/seedu/duke/exception/ParseAddClientException.java
  src/main/java/seedu/duke/exception/ParseAddPropertyException.java
  src/main/java/seedu/duke/parsermanager/ParseAdd.java
  src/main/java/seedu/duke/parsermanager/ParseAddClient.java
  src/main/java/seedu/duke/parsermanager/ParseAddProperty.java
  src/main/java/seedu/duke/parsermanager/ParsePair.java
  src/main/java/seedu/duke/parsermanager/ParseUnpair.java
  src/main/java/seedu/duke/parsermanager/Parser.java
Labels: type.Chore, priority.Medium

#186 Fix Check sections of UG
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#188 Reduce coupling for exception handling in Storage and Find Function
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/CommandFindClient.java
  src/main/java/seedu/duke/command/CommandFindProperty.java
  src/main/java/seedu/duke/exception/parsefindexception/FindEmptyDescriptionException.java
  src/main/java/seedu/duke/exception/parsefindexception/FindIncorrectNumOfTagException.java
  src/main/java/seedu/duke/exception/parsefindexception/ParseFindException.java
  src/main/java/seedu/duke/exception/storagexception/ClientFileNotFoundException.java
  src/main/java/seedu/duke/exception/storagexception/InvalidClientFormatException.java
  src/main/java/seedu/duke/exception/storagexception/InvalidClientTextException.java
  src/main/java/seedu/duke/exception/storagexception/InvalidPairingClientException.java
  src/main/java/seedu/duke/exception/storagexception/InvalidPairingPropertyException.java
  src/main/java/seedu/duke/exception/storagexception/PairFileNotFoundException.java
  src/main/java/seedu/duke/exception/storagexception/PropertyFileNotFoundException.java
  src/main/java/seedu/duke/exception/storagexception/StorageException.java
  src/main/java/seedu/duke/parsermanager/ParseAddClient.java
  src/main/java/seedu/duke/parsermanager/ParseAddProperty.java
  src/main/java/seedu/duke/parsermanager/ParseFindClient.java
  src/main/java/seedu/duke/parsermanager/ParseFindProperty.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
Labels: type.Chore, priority.Medium

#190 UG - Fix Quick Start section and broken link to releases
  docs/UserGuide.md
Labels: type.Bug, severity.Low

#192 Print no pairings message when checking a client with no pairs
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/check/CommandCheckClient.java
Labels: type.Bug, severity.Medium

#191 Add Delete Client/Property section in User Guide
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#193 Expand test coverage for Storage feature
  src/test/java/seedu/duke/CheckFileCreationTest.java
  src/test/java/seedu/duke/StorageTest.java
Labels: type.Chore, priority.Low

#194 Fix case insensitive address duplication bug
  src/main/java/seedu/duke/parsermanager/ParseAddProperty.java
Labels: type.Bug, severity.High

#195 Fix incorrectly rendered tables in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow
