Repository AY2223S1-CS2113-F11-1/tp, pull requests merged in 2022-11, with the labels that each got.

#205 Optimize add-related error messages
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/parsermanager/ParseAddClient.java
  src/main/java/seedu/duke/parsermanager/ParseAddProperty.java
Labels: type.Bug, severity.Medium

#206 Fix coding standard violations for ParseAddProperty, Property and Client
  src/main/java/seedu/duke/Client.java
  src/main/java/seedu/duke/Property.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/parsermanager/ParseAddClient.java
  src/main/java/seedu/duke/parsermanager/ParseAddProperty.java
Labels: severity.Medium

#208 Add validation between unit type and address format when adding property
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/exception/AddressFormatUnitTypeMismatchException.java
  src/main/java/seedu/duke/parsermanager/ParseAddProperty.java
Labels: type.Bug, severity.High

#209 Redraw Storage and Find feature's Sequence diagram using UML
  docs/diagrams/DeleteClientStorageSequenceDiagram.png
  docs/diagrams/FindClientSequenceDiagram.png
  docs/diagrams/FindPropertySequenceDiagram.png
  docs/diagrams/PlantUML File/ArchitectureDiagram.puml
  docs/diagrams/PlantUML File/FindClientSequenceDiagram.puml
  docs/diagrams/PlantUML File/FindPropertySequenceDiagram.puml
  docs/diagrams/PlantUML File/PairingListAddSD.puml
  docs/diagrams/PlantUML File/PairingListCD.puml
  docs/diagrams/PlantUML File/StorageAddClientSequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageAddPairSequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageAddPropertySequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageUpdateClientSequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageUpdatePairSequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageUpdatePropertySequenceDiagram.puml
  docs/diagrams/PlantUML File/style.puml
  docs/diagrams/StorageAddClientSequenceDiagram.jpg
  docs/diagrams/StorageAddClientSequenceDiagram.png
  docs/diagrams/StorageAddPairSequenceDiagram.jpg
  docs/diagrams/StorageAddPairSequenceDiagram.png
  docs/diagrams/StorageAddPropertySequenceDiagram.jpg
  docs/diagrams/StorageAddPropertySequenceDiagram.png
  docs/diagrams/StorageUpdateClientSD.jpg
  docs/diagrams/StorageUpdateClientSequenceDiagram.png
  docs/diagrams/StorageUpdatePairSD.jpg
  docs/diagrams/StorageUpdatePairSequenceDiagram.png
  docs/diagrams/StorageUpdatePropertySD.jpg
  docs/diagrams/StorageUpdatePropertySequenceDiagram.png
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/CommandFindClient.java
  src/main/java/seedu/duke/command/CommandFindProperty.java
Labels: priority.Medium

#220 Show error message when there are extra flags for Delete Client/Property
  src/main/java/seedu/duke/exception/ExtraFlagsException.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteClient.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteProperty.java
Labels: type.Bug, severity.Medium

#211 Improve code quality and improve messages
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/PairingList.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/exception/check/CheckNotIntegerException.java
  src/main/java/seedu/duke/parsermanager/ParseCheckProperty.java
  src/main/java/seedu/duke/parsermanager/Parser.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
  src/main/java/seedu/duke/parsermanager/pairunpair/PairParser.java
  src/main/java/seedu/duke/parsermanager/pairunpair/PairUnpairParser.java
  src/main/java/seedu/duke/parsermanager/pairunpair/UnpairParser.java
Labels: type.Bug, severity.Low

#213 Update DG for PairingList and check property
  docs/DeveloperGuide.md
  docs/diagrams/PairingListAPICD.png
  docs/diagrams/PairingListAddPairSD.png
  docs/diagrams/PairingListCD.png
  docs/diagrams/PairingListPairSD.png
  docs/diagrams/PlantUML File/PairingListAPICD.puml
  docs/diagrams/PlantUML File/PairingListAddSD.puml
  docs/diagrams/PlantUML File/PairingListCD.puml
  docs/diagrams/PlantUML File/PairingListPairSD.puml
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/command/pairunpair/CommandPair.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
  src/main/java/seedu/duke/parsermanager/pairunpair/PairParser.java
  src/main/java/seedu/duke/parsermanager/pairunpair/UnpairParser.java
Labels: type.Chore, priority.High

#224 Add PPP draft for OVReader
  docs/team/ovreader.md
Labels: type.Chore, priority.High

#219 Ng De Qi PPP
  docs/team/ngdeqi.md
Labels: type.Chore, priority.High

#225 UG - Add expected output for pair, unpair and check property
  docs/UserGuide.md
Labels: type.Chore, severity.Low

#227 Add non functional requirement and finding function to manual testing…
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#230 Add FeliciaBeatrice author tags
  src/main/java/seedu/duke/ClientList.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/PropertyList.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/CommandDelete.java
  src/main/java/seedu/duke/command/CommandDeleteClient.java
  src/main/java/seedu/duke/command/CommandDeleteProperty.java
  src/main/java/seedu/duke/command/check/CommandCheckClient.java
  src/main/java/seedu/duke/exception/ExtraFlagsException.java
  src/main/java/seedu/duke/parsermanager/ParseCheckClient.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteClient.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteProperty.java
Labels: type.Chore, priority.Low

#231 Edit check property feature for new check flag and handle extra parameters
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/CommandStructure.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/exception/check/CheckExtraParametersException.java
  src/main/java/seedu/duke/parsermanager/ParseCheckProperty.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
Labels: type.Bug, severity.Low

#233 Add checks for extra arguments for pair and unpair
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/exception/pairunpair/PairUnpairNotIntegerException.java
  src/main/java/seedu/duke/exception/pairunpair/pair/PairExtraArgumentsException.java
  src/main/java/seedu/duke/exception/pairunpair/unpair/UnpairExtraArgumentsException.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
  src/main/java/seedu/duke/parsermanager/pairunpair/PairParser.java
  src/main/java/seedu/duke/parsermanager/pairunpair/PairUnpairParser.java
  src/main/java/seedu/duke/parsermanager/pairunpair/UnpairParser.java
Labels: type.Bug, severity.Medium

#229 Implement Help Function to help user get a list of available commands
  .gitignore
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/CommandStructure.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/CommandHelp.java
  src/main/java/seedu/duke/exception/helpexception/UnwantedTextException.java
  src/main/java/seedu/duke/exception/storageexception/ClientFileNotFoundException.java
  src/main/java/seedu/duke/exception/storageexception/InvalidClientFormatException.java
  src/main/java/seedu/duke/exception/storageexception/InvalidClientTextException.java
  src/main/java/seedu/duke/exception/storageexception/InvalidPairingClientException.java
  src/main/java/seedu/duke/exception/storageexception/InvalidPairingPropertyException.java
  src/main/java/seedu/duke/exception/storageexception/PairFileNotFoundException.java
  src/main/java/seedu/duke/exception/storageexception/PropertyFileNotFoundException.java
  src/main/java/seedu/duke/exception/storageexception/StorageException.java
  src/main/java/seedu/duke/parsermanager/ParseHelp.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
Labels: type.Chore, priority.Medium

#232 Update Developer Guide with Find feature and fix incorrect UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/FindClientSequenceDiagram.png
  docs/diagrams/FindPropertySequenceDiagram.png
  docs/diagrams/PlantUML File/FindClientSequenceDiagram.puml
  docs/diagrams/PlantUML File/FindPropertySequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageAddClientSequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageAddPairSequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageAddPropertySequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageUpdateClientSequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageUpdatePairSequenceDiagram.puml
  docs/diagrams/PlantUML File/StorageUpdatePropertySequenceDiagram.puml
  docs/diagrams/StorageAddClientSequenceDiagram.png
  docs/diagrams/StorageAddPairSequenceDiagram.png
  docs/diagrams/StorageAddPropertySequenceDiagram.png
  docs/diagrams/StorageUpdateClientSequenceDiagram.png
  docs/diagrams/StorageUpdatePairSequenceDiagram.png
  docs/diagrams/StorageUpdatePropertySequenceDiagram.png
Labels: type.Chore, priority.High

#235 FeliciaBeatrice PPP
  docs/team/feliciabeatrice.md
Labels: type.Chore, priority.High

#236 Change the file name for Wilson's PPP
  docs/team/wilsonngja.md
Labels: priority.High

#237 Change Check Client command format
  docs/UserGuide.md
  src/main/java/seedu/duke/CommandStructure.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/parsermanager/ParseCheckClient.java
Labels: type.Bug, severity.Low

#240 Fix Coding Standard Violations
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/CommandDeleteClient.java
  src/main/java/seedu/duke/command/CommandDeleteProperty.java
  src/main/java/seedu/duke/parsermanager/ParseCheckClient.java
Labels: type.Bug, severity.Low

#250 Add testing for ParseAddClient
  src/main/java/seedu/duke/parsermanager/ParseAddClient.java
  src/test/java/seedu/duke/command/CommandAddClientTest.java
  src/test/java/seedu/duke/command/CommandAddPropertyTest.java
  src/test/java/seedu/duke/parsermanager/ParseAddClientTest.java
Labels: type.Chore, priority.Medium

#252 Add testing for ParseAddProperty
  src/test/java/seedu/duke/parsermanager/ParseAddPropertyTest.java
Labels: type.Chore, priority.Medium

#239 Include Expected output for add client and property
  docs/Storage File Screenshot/client.jpg
  docs/Storage File Screenshot/pair.jpg
  docs/Storage File Screenshot/property.jpg
  docs/UserGuide.md
  src/main/java/seedu/duke/command/CommandAddClient.java
  src/main/java/seedu/duke/command/CommandAddProperty.java
Labels: priority.Medium

#258 Update Add Features Sections in User Guide
  docs/UserGuide.md
  src/main/java/seedu/duke/Ui.java
  src/test/java/seedu/duke/parsermanager/ParseAddClientTest.java
  src/test/java/seedu/duke/parsermanager/ParseAddPropertyTest.java
Labels: type.Chore, priority.High

#238 Change Delete Client/Property commands format
  docs/UserGuide.md
  src/main/java/seedu/duke/CommandStructure.java
  src/main/java/seedu/duke/Messages.java
  src/main/java/seedu/duke/exception/check/checkproperty/CheckPropertyMissingFlagException.java
  src/main/java/seedu/duke/parsermanager/ParseCheckClient.java
  src/main/java/seedu/duke/parsermanager/ParseCheckProperty.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteClient.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteProperty.java
Labels: type.Bug, severity.Low

#243 Use PlantUML for Delete Client/Property Sequence Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/DeleteClientSD.png
  docs/diagrams/DeletePropertySD.png
  docs/diagrams/PlantUML File/DeleteClientSequenceDiagram.puml
  docs/diagrams/PlantUML File/DeletePropertySequenceDiagram.puml
Labels: type.Bug, severity.Low

#247 Rename FindParser class name to improve readability
  src/main/java/seedu/duke/parsermanager/ParserManager.java
  src/main/java/seedu/duke/parsermanager/find/CommandFindClientParser.java
  src/main/java/seedu/duke/parsermanager/find/CommandFindPropertyParser.java
  src/test/java/seedu/duke/FindFunctionTest.java
Labels: type.Bug, severity.Medium

#253 Add help as a feature in PPP
  docs/team/wilsonngja.md
Labels: type.Chore, priority.Medium

#255 Remove input lines from expected output codeblock in find and help co…
  docs/UserGuide.md
Labels: type.Chore, priority.Medium

#260 Fix add related coding standard violations
  docs/DeveloperGuide.md
  docs/diagrams/CommandAddParserRelatedClassesDiagram.png
  docs/diagrams/ParseAddRelatedClassesDiagram.png
  docs/diagrams/PlantUML File/CommandAddParserRelatedClassesDiagram.puml
  src/main/java/seedu/duke/Client.java
  src/main/java/seedu/duke/ClientList.java
  src/main/java/seedu/duke/Property.java
  src/main/java/seedu/duke/PropertyList.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/add/CommandAdd.java
  src/main/java/seedu/duke/command/add/CommandAddClient.java
  src/main/java/seedu/duke/command/add/CommandAddProperty.java
  src/main/java/seedu/duke/exception/ParseAddClientException.java
  src/main/java/seedu/duke/exception/ParseAddPropertyException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddclientexception/DuplicateClientException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddclientexception/EmptyAddClientDetailException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddclientexception/IncorrectAddClientFlagOrderException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddclientexception/InvalidBudgetFormatException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddclientexception/InvalidContactNumberException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddclientexception/InvalidEmailException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddclientexception/MissingAddClientFlagException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddclientexception/ParseAddClientException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddpropertyexception/AddressFormatUnitTypeMismatchException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddpropertyexception/DuplicatePropertyException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddpropertyexception/EmptyAddPropertyDetailException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddpropertyexception/IncorrectAddPropertyFlagOrderException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddpropertyexception/InvalidPriceFormatException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddpropertyexception/InvalidSingaporeAddressException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddpropertyexception/InvalidUnitTypeLabelException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddpropertyexception/MissingAddPropertyFlagException.java
  src/main/java/seedu/duke/exception/parseaddexception/parseaddpropertyexception/ParseAddPropertyException.java
  src/main/java/seedu/duke/parsermanager/Parser.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
  src/main/java/seedu/duke/parsermanager/add/CommandAddClientParser.java
  src/main/java/seedu/duke/parsermanager/add/CommandAddParser.java
  src/main/java/seedu/duke/parsermanager/add/CommandAddPropertyParser.java
  src/test/java/seedu/duke/command/CommandAddClientTest.java
  src/test/java/seedu/duke/command/CommandAddPropertyTest.java
  src/test/java/seedu/duke/parsermanager/CommandAddClientParserTest.java
  src/test/java/seedu/duke/parsermanager/CommandAddPropertyParserTest.java
Labels: type.Chore, priority.High

#261 Final checks
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/PairingListCD.png
  docs/diagrams/PairingListPairSD.png
  docs/diagrams/PlantUML File/PairingListCD.puml
  docs/diagrams/PlantUML File/PairingListPairSD.puml
  docs/team/johndoe.md
  src/main/java/seedu/duke/CommandStructure.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/PairingList.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/check/CommandCheckProperty.java
  src/main/java/seedu/duke/command/pairunpair/CommandPair.java
  src/main/java/seedu/duke/command/pairunpair/CommandPairUnpair.java
  src/main/java/seedu/duke/command/pairunpair/CommandUnpair.java
  src/main/java/seedu/duke/exception/check/CommandCheckExtraParametersException.java
  src/main/java/seedu/duke/exception/check/CommandCheckNotIntegerException.java
  src/main/java/seedu/duke/exception/check/checkproperty/CheckPropertyMissingFlagException.java
  src/main/java/seedu/duke/exception/pairunpair/PairUnpairNotIntegerException.java
  src/main/java/seedu/duke/exception/pairunpair/ParsePairUnpairException.java
  src/main/java/seedu/duke/exception/pairunpair/pair/BudgetExceededException.java
  src/main/java/seedu/duke/exception/pairunpair/pair/PairMissingDescriptionException.java
  src/main/java/seedu/duke/exception/pairunpair/pair/PairMissingFlagException.java
  src/main/java/seedu/duke/exception/pairunpair/unpair/NoExistingPairException.java
  src/main/java/seedu/duke/exception/pairunpair/unpair/UnpairMissingFlagException.java
  src/main/java/seedu/duke/parsermanager/CommandCheckPropertyParser.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
  src/main/java/seedu/duke/parsermanager/pairunpair/CommandPairParser.java
  src/main/java/seedu/duke/parsermanager/pairunpair/CommandPairUnpairParser.java
  src/main/java/seedu/duke/parsermanager/pairunpair/CommandUnpairParser.java
  src/test/java/seedu/duke/PairingListTest.java
Labels: priority.High

#262 Improve coding standard by removing magic literals
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/CommandFindClient.java
  src/main/java/seedu/duke/command/CommandFindProperty.java
  src/main/java/seedu/duke/parsermanager/find/CommandFindClientParser.java
  src/main/java/seedu/duke/parsermanager/find/CommandFindPropertyParser.java
Labels: type.Bug, priority.Medium

#263 Fix even more minor issues in docs
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/team/ngdeqi.md
Labels: priority.High

#264 Remove additional ordered list in PPP
  docs/team/wilsonngja.md
Labels: type.Bug, severity.Low

#266 Even more minor formatting issues UG DG ngdeqi PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ngdeqi.md
Labels: priority.High

#271 Developer guide update to fix NFR bugs
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High, severity.Medium

#265 Branch about us
  docs/AboutUs.md
Labels: type.Chore, priority.Medium

#268 Add Manual Testing Instructions for Add Client/Property
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#272 Fix minor code quality issues
  src/main/java/seedu/duke/CommandStructure.java
  src/main/java/seedu/duke/parsermanager/CommandCheckPropertyParser.java
  src/main/java/seedu/duke/parsermanager/ParseCheckClient.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteClient.java
  src/main/java/seedu/duke/parsermanager/ParseDeleteProperty.java
Labels: type.Bug, severity.Low

#270 Add details in glossary (DG)
  docs/DeveloperGuide.md
Labels: type.Chore, priority.Medium

#280 Update PPP
  docs/DeveloperGuide.md
  docs/team/ovreader.md
  src/main/java/seedu/duke/parsermanager/Parser.java
Labels: type.Chore, priority.High

#282 Add page break for PPP (OVReader)
  docs/team/ovreader.md
Labels: type.Chore, priority.Medium

#281 Update manual testing section in DG
  docs/DeveloperGuide.md
Labels: type.Chore, priority.Medium

#283 Add test code for Delete and Check
  src/main/java/seedu/duke/command/check/CommandCheckClient.java
  src/test/java/seedu/duke/CheckTest.java
  src/test/java/seedu/duke/DeleteTest.java
Labels: type.Chore, priority.Medium

#284 Remove icon for Add Command related class diagram in DeveloperGuide.md
  docs/diagrams/CommandAddParserRelatedClassesDiagram.png
  docs/diagrams/CommandAddRelatedClassesDiagram.png
  docs/diagrams/PlantUML File/CommandAddParserRelatedClassesDiagram.puml
  docs/diagrams/PlantUML File/CommandAddRelatedClassesDiagram.puml
Labels: type.Bug, severity.Medium

#285 Fix minor UG and DG issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteClientSD.png
  docs/diagrams/DeletePropertySD.png
  docs/diagrams/PlantUML File/DeleteClientSequenceDiagram.puml
  docs/diagrams/PlantUML File/DeletePropertySequenceDiagram.puml
Labels: type.Bug, severity.Low

#286 Fix rendering issue where image does not appear on Github Pages
  docs/DeveloperGuide.md
Labels: type.Bug, severity.High

#287 Add new line after AddClient and AddProperty image
  docs/DeveloperGuide.md
Labels: severity.Medium

#288 Update Delete Class Diagram
  docs/diagrams/DeleteClientPropertyCD.png
Labels: type.Bug, severity.Low

#289 Add Singapore context description to UG and README
  docs/README.md
  docs/UserGuide.md
Labels: priority.Medium

#291 Fix valid input space bug along with some coding violations
  src/main/java/seedu/duke/Ui.java
Labels: type.Bug, severity.Medium

#292 Fix bug that cause program to crash when backslash is placed after command
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/exception/InvalidCommandException.java
  src/main/java/seedu/duke/parsermanager/CommandHelpParser.java
  src/main/java/seedu/duke/parsermanager/ParserManager.java
Labels: type.Bug, severity.High
